/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mapaia.frame;

import com.mycompany.mapaia.ArbolB.ArbolB;
import com.mycompany.mapaia.frame.diseño.Iconos;
import com.mycompany.mapaia.grafo.Grafo;
import com.mycompany.mapaia.grafo.Nodo;
import com.mycompany.mapaia.lectorgrafo.Lector;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeModel;

/**
 * 
 * @author mari2bar
 */
public class MapaFrame extends javax.swing.JFrame {

    /**
     * Creates new form MapaFrame
     */
    private Grafo grafo;
    
    public MapaFrame() {
        JFrame.setDefaultLookAndFeelDecorated(true);
        initComponents();
        ImageIcon i = new ImageIcon(getClass().getResource("/a.png"));
        Image ima = i.getImage().getScaledInstance(50, 30, Image.SCALE_DEFAULT);
        this.setIconImage(i.getImage());
        this.setLocationRelativeTo(null);
        Iconos icon = new Iconos();
        icon.ingresarIconos(tabbedArbolB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        spGrafo = new javax.swing.JScrollPane();
        pnlGrafo = new javax.swing.JPanel();
        tabbedArbolB = new javax.swing.JTabbedPane();
        comboCaminar = new javax.swing.JComboBox<>();
        txtDestino = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemLeer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGrafo.setBackground(new java.awt.Color(193, 174, 188));

        javax.swing.GroupLayout pnlGrafoLayout = new javax.swing.GroupLayout(pnlGrafo);
        pnlGrafo.setLayout(pnlGrafoLayout);
        pnlGrafoLayout.setHorizontalGroup(
            pnlGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        pnlGrafoLayout.setVerticalGroup(
            pnlGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        spGrafo.setViewportView(pnlGrafo);

        tabbedArbolB.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        comboCaminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spGrafo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabbedArbolB)
                    .addComponent(comboCaminar, 0, 282, Short.MAX_VALUE)
                    .addComponent(txtDestino))
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spGrafo)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(tabbedArbolB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboCaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu1.setText("Options");

        itemLeer.setText("Leer Archivo");
        itemLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLeerActionPerformed(evt);
            }
        });
        jMenu1.add(itemLeer);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLeerActionPerformed
        // TODO add your handling code here:
        Lector lector = new Lector();
        grafo = lector.leerArchivo();
        //grafo.grafico();
        spGrafo.setViewportView(grafo);
        spGrafo.repaint();
        BufferedImage bfi = new BufferedImage(550, 550, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = bfi.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(193, 174, 188));
        g2.fillRect(0, 0, this.getWidth(), this.getHeight());
        grafo.dibujarNodos(g2);
        grafo.desmarcarAristas();
        g2.dispose();
        File file = new File("/home/mari2bar/Documentos/Proyectos/Estructura de Datos/Mapa/MapaIA/src/main/resources/Grafo/grafo.png");
        file.delete();
        try {
            ImageIO.write(bfi, "png", file);
            grafo.ingresarLabel();
            //spGrafo.setViewportView(grafo);
            //spGrafo.repaint();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_itemLeerActionPerformed

    public void ingresarPosibilidadesPie(){
        ArbolB b = grafo.caminosNodo(grafo.getPosicionado(), new Nodo(txtDestino.getText()), "pie");
        if(b!=null){
            JPanel nuevo = new JPanel();
            b.ingresarArbol(nuevo);
            tabbedArbolB.setComponentAt(0, nuevo);
        }
    }
 
    public void ingresarPosibilidadesCarro(){
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCaminar;
    private javax.swing.JMenuItem itemLeer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlGrafo;
    private javax.swing.JScrollPane spGrafo;
    private javax.swing.JTabbedPane tabbedArbolB;
    private javax.swing.JTextField txtDestino;
    // End of variables declaration//GEN-END:variables
}
